# it is numerical python
# NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]
ar = np.array(l)
type(ar)

numpy.ndarray

In [3]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
a = [2,3,4]
np.asanyarray(a)

array([2, 3, 4])

In [7]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [9]:
# it cannot convert to array beacuse it is subset of array
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [11]:
a = np.array([1,2,3,4])

In [12]:
a

array([1, 2, 3, 4])

In [13]:
c = a
c

array([1, 2, 3, 4])

In [14]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [15]:
iterable = (i*i for i in range(5))

In [16]:
np.fromiter(iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [17]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [18]:
np.fromstring('234,234',sep=',')

array([234., 234.])

In [19]:
#numpy - dataType

In [25]:
l = [2,3,4,5,6]
ar = np.array(l)
ar.ndim

1

In [27]:
l1 = [[2,3,4,5,6],[2,3,4,5,6]]
ar1 = np.array(l1)
ar1.ndim

2

In [28]:
ar1.size

10

In [29]:
ar1.shape

(2, 5)

In [30]:
list(range(5))

[0, 1, 2, 3, 4]

In [34]:
np.arange(1.3 , 22.3)

array([ 1.3,  2.3,  3.3,  4.3,  5.3,  6.3,  7.3,  8.3,  9.3, 10.3, 11.3,
       12.3, 13.3, 14.3, 15.3, 16.3, 17.3, 18.3, 19.3, 20.3, 21.3])

In [35]:
#produce 10 data 
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [36]:
# these all are data generator function

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((2,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
# so there are many function np.eye , np.logspace , np.linespace 

In [47]:
arr = np.random.randn(3,4)
arr

array([[-0.86366418, -0.07131505,  1.99217283, -1.6786487 ],
       [-0.21132219,  0.59483134, -0.38117228, -1.50934484],
       [-0.96752012,  0.72409655, -0.14342682, -1.2056657 ]])

In [45]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0  1.453510  0.904070  1.876184  1.286592
1 -0.991484  0.259381  1.754411 -0.540666
2 -0.098467  0.182900  0.243159  0.802761

In [56]:
arr1 = np.random.randint(1,100,(1000,1000))
df1 = pd.DataFrame(arr1)

In [57]:
df1

0    1    2    3    4    5    6    7    8    9    10   ...  989  990  991  992  993  994  995  996  997  998  999
0     15   86   15    9   14   26   48   76   64   79   86  ...   71   76   48   51   81   43   63   82   54   28   97
1     61   29   67   67   99   61   38   54   46   39   32  ...   29    3   76   87   73   36   43   34   47   89   51
2      4   82   80   90   35   59   84    6   53   77    6  ...   97   70   77    6   87    7   66    6   33   84   37
3     97   78   62   51   12    2   42   49   13   25   49  ...   77    5   73   84   39   20   43   96   34    5   30
4     47   28   13   52   75   19   90   84   26   59   16  ...   98   25   62   57   23   36   53   25   94   75   11
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
995   78    2   29   43   22   82   11   49   25   82   71  ...   54    9   69   70   78   90   44   37   35   23   51
996   28   40   43    5    7   62    1   65    7   60   74  ...   26   30   38   60   53   18   53   86   19   97   81
997   36   97   86   61   52   32    3   81   35   91   87  ...   95   96   83   26   66   31   11   38   58   98   82
998   98   85   49   34    6   41   16   84   67    6   86  ...   54   62   88   90   40   34   50   84   16   47   51
999   22   77   78   94   43   28   83    6   75   87   58  ...   91   27   30   14   10    9   76   12   25   14   28

[1000 rows x 1000 columns]

In [58]:
df1.to_csv('test.csv')

In [60]:
arr = np.random.rand(3,4)
arr

array([[0.29362868, 0.08754383, 0.54798607, 0.60920757],
       [0.70160027, 0.10831288, 0.54566254, 0.91910096],
       [0.35286716, 0.66033383, 0.10425222, 0.84025406]])

In [61]:
arr.reshape(6,2)

array([[0.29362868, 0.08754383],
       [0.54798607, 0.60920757],
       [0.70160027, 0.10831288],
       [0.54566254, 0.91910096],
       [0.35286716, 0.66033383],
       [0.10425222, 0.84025406]])

In [62]:
# this will only work is data is in correct size

In [65]:
arr = np.random.randint(1,100,(5,5))
arr

array([[46, 80, 62, 93, 37],
       [37, 50, 64, 60, 64],
       [99, 82, 30, 51, 35],
       [ 8, 47, 64, 89, 70],
       [94, 61, 90, 21, 50]])

In [66]:
arr[arr>50]

array([80, 62, 93, 64, 60, 64, 99, 82, 51, 64, 89, 70, 94, 61, 90])

In [67]:
arr[2:4 , [1,2]]

array([[82, 30],
       [47, 64]])

In [68]:
arr[0][0] = 5000

In [69]:
arr

array([[5000,   80,   62,   93,   37],
       [  37,   50,   64,   60,   64],
       [  99,   82,   30,   51,   35],
       [   8,   47,   64,   89,   70],
       [  94,   61,   90,   21,   50]])

In [75]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [76]:
arr1

array([[6, 2, 1],
       [7, 1, 7],
       [6, 2, 1]])

In [77]:
arr2

array([[5, 3, 9],
       [9, 8, 6],
       [5, 8, 9]])

In [78]:
arr1+arr2

array([[11,  5, 10],
       [16,  9, 13],
       [11, 10, 10]])

In [79]:
arr1 * arr2

array([[30,  6,  9],
       [63,  8, 42],
       [30, 16,  9]])

In [80]:
arr1 @ arr2

array([[ 53,  42,  75],
       [ 79,  85, 132],
       [ 53,  42,  75]])

In [81]:
arr1 ** 2

array([[36,  4,  1],
       [49,  1, 49],
       [36,  4,  1]])

In [82]:
arr1

array([[6, 2, 1],
       [7, 1, 7],
       [6, 2, 1]])

In [83]:
# numpy - broadcasting

In [96]:
arr = np.zeros((4,4))

In [97]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
row = np.array([1,2,3,4])

In [87]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [88]:
arr.shape

(4, 4)

In [89]:
row

array([1, 2, 3, 4])

In [91]:
row.T
# it will not transpose because it is not 2d

array([1, 2, 3, 4])

In [93]:
col = np.array([[1,2,3,4]])

In [94]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [99]:
arr + col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [101]:
arr1 = np.random.randint(1,10,(3,3))

In [103]:
np.sqrt(arr1)

array([[1.41421356, 2.23606798, 1.73205081],
       [2.        , 2.44948974, 1.73205081],
       [3.        , 2.44948974, 2.        ]])

In [104]:
np.log10(arr1)

array([[0.30103   , 0.69897   , 0.47712125],
       [0.60205999, 0.77815125, 0.47712125],
       [0.95424251, 0.77815125, 0.60205999]])