# Array Manipulation

In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,10,(3,4))

In [6]:
arr

array([[7, 6, 6, 7],
       [3, 3, 5, 5],
       [9, 4, 5, 1]])

In [7]:
arr.reshape(6,2)

array([[7, 6],
       [6, 7],
       [3, 3],
       [5, 5],
       [9, 4],
       [5, 1]])

In [8]:
arr.reshape(2,6)

array([[7, 6, 6, 7, 3, 3],
       [5, 5, 9, 4, 5, 1]])

In [10]:
arr

array([[7, 6, 6, 7],
       [3, 3, 5, 5],
       [9, 4, 5, 1]])

In [12]:
# doing transpose
arr.T

array([[7, 3, 9],
       [6, 3, 4],
       [6, 5, 5],
       [7, 5, 1]])

In [14]:
arr.flatten()  # It does in single lone

array([7, 6, 6, 7, 3, 3, 5, 5, 9, 4, 5, 1])

In [15]:
arr1 = np.array([1,2,3,4,5])

In [16]:
arr1.ndim

1

In [17]:
np.expand_dims(arr1 , axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
arr

array([[7, 6, 6, 7],
       [3, 3, 5, 5],
       [9, 4, 5, 1]])

In [20]:
np.squeeze(arr) 

array([[7, 6, 6, 7],
       [3, 3, 5, 5],
       [9, 4, 5, 1]])

In [23]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [27]:
arr2 = np.squeeze(data)

In [29]:
np.repeat(arr , 1)

array([7, 6, 6, 7, 3, 3, 5, 5, 9, 4, 5, 1])

In [30]:
# Numpy - Binary Operation

In [32]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [37]:
arr1

array([[1, 6, 1, 9],
       [7, 5, 8, 8],
       [1, 1, 1, 5]])

In [38]:
arr2

array([[6, 7, 9, 2],
       [4, 5, 6, 2],
       [4, 9, 3, 3]])

In [39]:
~arr1

array([[ -2,  -7,  -2, -10],
       [ -8,  -6,  -9,  -9],
       [ -2,  -2,  -2,  -6]])

In [40]:
arr1 | arr2

array([[ 7,  7,  9, 11],
       [ 7,  5, 14, 10],
       [ 5,  9,  3,  7]])

In [41]:
arr1 > arr2

array([[False, False, False,  True],
       [ True, False,  True,  True],
       [False, False, False,  True]])

In [42]:
# Numpy - String Function

In [51]:
arr = np.array(['sudh' , 'akumar'])

In [52]:
np.char.upper(arr)

array(['SUDH', 'AKUMAR'], dtype='<U6')

In [53]:
np.char.title(arr)

array(['Sudh', 'Akumar'], dtype='<U6')

In [54]:
np.char.capitalize(arr)

array(['Sudh', 'Akumar'], dtype='<U6')

In [55]:
# Numpy - Mathematical Function

In [56]:
arr1 

array([[1, 6, 1, 9],
       [7, 5, 8, 8],
       [1, 1, 1, 5]])

In [57]:
np.sin(arr1)

array([[ 0.84147098, -0.2794155 ,  0.84147098,  0.41211849],
       [ 0.6569866 , -0.95892427,  0.98935825,  0.98935825],
       [ 0.84147098,  0.84147098,  0.84147098, -0.95892427]])

In [58]:
np.power(arr1,2)

array([[ 1, 36,  1, 81],
       [49, 25, 64, 64],
       [ 1,  1,  1, 25]], dtype=int32)

In [59]:
np.mean(arr1)

4.416666666666667

In [60]:
# Sort Search Count

In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [3]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [4]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [6]:
np.searchsorted(arr , 5)

8

In [7]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [8]:
np.count_nonzero(arr1)

2

In [10]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [11]:
np.where(arr>6)

(array([5, 8], dtype=int64),)

In [15]:
arr2 = np.extract(arr>6 , arr)
arr2

array([ 72, 455])

In [16]:
# numpy - byte swapping

In [17]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

In [18]:
# if view is used then it is changed

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
b = arr.view()

In [22]:
b[0] = 500
b

array([500,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
arr

array([500,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [24]:
# if copy is used it is deep copy 
# view is swallow copy

In [25]:
# Numpy - Matrix library

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])